'''

'''

# ROOT_DIR = '/Users/wangzhongyi/Library/Mobile Documents/com~apple~CloudDocs/Documents/Johnnyiiiii/教学/课程/project/news'
# ROOT_DIR = 'D:/BaiduSyncdisk/data/news'
ROOT_DIR = 'D:/BaiduSyncdisk/data/news'

SOURCE_CNN = 'cnn'
SOURCE_BBC = 'bbc'
SOURCE_ABC = 'abc'
SOURCE_THE_JAPAN_TIMES = 'the-japan-times'
SOURCE_THE_KOREA_HERALD = 'the-korea-herald'
DIR_LIST = 'list'
DIR_DETAIL = 'detail'
DIR_PROCESSED = 'processed'
DIR_DEBUG = 'debug'
FILE_FAIL = 'fail.txt'
FILE_SUCCESS = 'success.txt'
FILE_AUDIO = 'audio.txt'
FILE_KEYWORDS_BY_SOURCE = 'keywords_by_source.json'
FILE_KEYWORDS_BY_DOC = 'keywords_by_doc.json'
DIR_WORDCLOUD = 'wordcloud'
DIR_CONTEXT = 'context'
DIR_SENTIMENT = 'sentiment'
DIR_APPRAISAL_ATTITUDE = 'appraisal_attitude'
SIZE = 10

NEW_COL_LEMMA_TEXT = '内容lemma后纯文本'
NEW_COL_NOISE_FLAG = '噪音行'
NEW_COL_CONTENT_CLEAN = '内容整行'
COL_ID = 'id'
COL_CONTENT = '内容'
COL_KEYWORD = '关键词'
COL_CONTEXT = '搭配词'
COL_POS = '词性'
COL_POSITION = '位置'
COL_SENT_INDEX = '行号'
COL_FREQUENCY = '词频'
COL_WORD = 'word'
COL_SUBSYSTEM = 'subsystem'
COL_TYPE = 'type'
COL_SUBTYPE = 'subtype'
COL_EVALUATION = 'evaluation'
NEW_COL_TITLE_LEMMA_TEXT = '标题lemma后纯文本'
NEW_COL_TITLE_CLUSTER = '根据标题聚类'
NEW_COL_CONTENT_CLUSTER = '根据内容聚类'
COL_SENTENCE = 'sentence'
COL_TITLE = '标题'
COL_TOPIC = '主题'
COL_STANCE = '立场'
LIMIT = 20
COL_CONTENT_EN = 'content'
